import crypto from 'node:crypto'
import { cleanText, evaluateAttestation, normalizeAttestation, reportMarkdown, resolveConfig } from './core.js'
import { inspectWorkspace, runMachineGate } from './runner.js'
const API='/api/completion-gate/v1/state'
const SOURCE={kind:'plugin',plugin:'dsh-completion-gate'}
export const name='completion-gate'
export const inject=['tools','commands','webServer','systemPrompt']
function key(a){return String(a?.id||a?.session?.header?.id||'unknown')}
function cwd(a){return String(a?.session?.header?.cwd||'')}
function isSubagent(a){const h=a?.session?.header;return Boolean(h?.parentSession)||Number(h?.delegationDepth||0)>0}
function json(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body))}
function sameOrigin(req){if(req.headers?.['sec-fetch-site']==='cross-site')return false;const o=req.headers?.origin,h=req.headers?.host;if(typeof o!=='string')return req.headers?.['sec-fetch-site']==='same-origin';try{return new URL(o).host===h}catch{return false}}
function contentOf(message){const text=[],reasoning=[];let toolCalls=0;for(const b of Array.isArray(message?.content)?message.content:[]){if(b?.type==='text'&&typeof b.text==='string')text.push(b.text);else if(b?.type==='reasoning'&&typeof b.text==='string')reasoning.push(b.text);else if(b?.type==='tool-call')toolCalls++}return{text:text.join('\n').trim(),reasoning:reasoning.join('\n').trim(),toolCalls}}
const FUTURE=[/\bnow\s+i\s+need\b/i,/\bnext\s+i(?:'ll|\s+will|\s+need\s+to)\b/i,/\bi\s+(?:still\s+)?need\s+to\b/i,/\blet\s+me\s+(?:check|inspect|trace|verify|test|run|search|read|look|implement|fix|continue|start|compare|review|open)\b/i,/\bi(?:'ll|\s+will)\s+(?:now\s+)?(?:check|inspect|trace|verify|test|run|search|read|look|implement|fix|continue|start|compare|review|open)\b/i,/\bin\s+parallel\b/i,/\bnext\s+step\b/i,/\bneed\s+to\s+(?:see|check|inspect|trace|verify|test|run|search|read|implement|fix)\b/i]
export function turnEvidence(agent,turn){const ev=Array.isArray(agent?.session?.events)?agent.session.events:[];const cur=ev.filter(e=>e?.data?.turn===turn),as=cur.filter(e=>e.type==='assistant/message'),tc=cur.filter(e=>e.type==='tool/call'),tr=cur.filter(e=>e.type==='tool/result');const content=contentOf(as.at(-1)?.data?.message),combined=`${content.text}\n${content.reasoning}`;return{assistantMessages:as.length,toolCalls:tc.length,toolResults:tr.length,text:content.text,reasoning:content.reasoning,futureIntent:FUTURE.some(re=>re.test(combined)),reasoningOnlyAfterTools:tc.length>0&&!!content.reasoning&&!content.text&&content.toolCalls===0}}
export class CompletionGateService{
 constructor(ctx,config={}){this.ctx=ctx;this.config=resolveConfig(config);this.states=new Map();this.disposers=[]}
 state(a){const k=key(a);if(!this.states.has(k))this.states.set(k,{baselineHead:'',baselineCaptured:false,cached:new Map(),attestation:null,override:null,lastReport:null,lastPass:'',autoBlocks:0,continuationTurn:0,continuationBlocks:0});return this.states.get(k)}
 applies(a){return this.config.gateSubagents||!isSubagent(a)}
 async baseline(a){if(!this.applies(a))return;const s=this.state(a);if(s.baselineCaptured)return;const dir=cwd(a);if(!dir){s.baselineCaptured=true;return}try{s.baselineHead=(await inspectWorkspace(dir,this.config)).head||''}finally{s.baselineCaptured=true}}
 async workspace(a){const dir=cwd(a);if(!dir)throw new Error('Completion Gate requires session.header.cwd');return inspectWorkspace(dir,this.config,this.state(a).baselineHead)}
 changed(ws,s){return ws.changedFiles.length>0||Boolean(s.baselineHead&&ws.head&&s.baselineHead!==ws.head)}
 decorate(machine,s,ws){const att=this.config.requireAttestation?evaluateAttestation(s.attestation,ws.changedFiles,ws.fingerprint):{pass:true,problems:[]};const blockers=[...machine.blockers,...(!att.pass?att.problems:[])],overridden=Boolean(s.override&&s.override.fingerprint===ws.fingerprint);return{...machine,pass:overridden||!blockers.length,blockers,attestation:att,overridden,generatedAt:Date.now()}}
 async run(a,signal,{force=false}={}){const s=this.state(a);await this.baseline(a);const ws=await this.workspace(a);if(!force&&this.config.gateOnlyChangedWorkspaces&&!this.changed(ws,s)){const r={workspaceLabel:ws.root.split(/[\\/]/).pop(),fingerprint:ws.fingerprint,pass:true,machinePass:true,skipped:true,changedFiles:ws.changedFiles,checks:[],todoHits:[],securityHits:[],blockers:[],attestation:{pass:true,problems:[]},generatedAt:Date.now()};s.lastReport=r;return r}let m=s.cached.get(ws.fingerprint);if(!m||force){m=await runMachineGate(ws,this.config,signal);s.cached.set(ws.fingerprint,m)}const r=this.decorate(m,s,ws);s.lastReport=r;return r}
 async attest(a,args){const s=this.state(a),ws=await this.workspace(a);s.attestation=normalizeAttestation(args,ws.fingerprint);let m=s.cached.get(ws.fingerprint);if(!m){m=await runMachineGate(ws,this.config,new AbortController().signal);s.cached.set(ws.fingerprint,m)}const r=this.decorate(m,s,ws);s.lastReport=r;return r}
 async override(a,reason){const s=this.state(a),ws=await this.workspace(a);s.override={fingerprint:ws.fingerprint,reason:cleanText(reason||'Operator override',1000),createdAt:Date.now()};return this.run(a,new AbortController().signal)}
 reset(a){const s=this.state(a);s.cached.clear();s.attestation=null;s.override=null;s.lastReport=null;s.autoBlocks=0;s.continuationTurn=0;s.continuationBlocks=0}
 premature(a,turn){if(!this.config.preventPrematureStops)return null;const s=this.state(a);if(s.continuationTurn!==turn){s.continuationTurn=turn;s.continuationBlocks=0}if(s.continuationBlocks>=this.config.prematureStopMaxContinuations)return null;const e=turnEvidence(a,turn);if(!e.futureIntent&&!e.reasoningOnlyAfterTools)return null;s.continuationBlocks++;return e}
 steerContinue(a,e){const why=e.reasoningOnlyAfterTools?'The latest step ended with reasoning after tool work but no user-facing completion.':'The latest response explicitly described pending next actions.';a.steer({id:crypto.randomUUID(),role:'user',content:[{type:'text',text:`PREMATURE STOP GUARD: Continue the unfinished task. ${why} Execute the pending investigation or implementation now. Do not summarize or claim completion yet.`}],source:SOURCE})}
 async stopping({agent,turn,signal}){if(!this.config.enabled||!this.applies(agent))return;const p=this.premature(agent,turn);if(p){this.steerContinue(agent,p);return}let r;try{r=await this.run(agent,signal)}catch(e){if(this.config.mode==='strict')agent.steer({id:crypto.randomUUID(),role:'user',content:[{type:'text',text:`Completion Gate could not evaluate the workspace: ${cleanText(e?.message||e,1000)}. Investigate before claiming completion.`}],source:SOURCE});return}if(r.pass)return;if(this.config.mode==='advisory')return;this.state(agent).autoBlocks++;agent.steer({id:crypto.randomUUID(),role:'user',content:[{type:'text',text:`COMPLETION GATE BLOCKED. Do not claim completion.\n\n${r.blockers.map(x=>`- ${x}`).join('\n')}\n\nFix the failures, review every changed file, then call completion_gate with action=attest and concrete acceptance-criteria evidence.`}],source:SOURCE})}
 snapshot(){const sessions=[];for(const[id,s]of this.states)if(s.lastReport)sessions.push({sessionId:id,pass:s.lastReport.pass,workspaceLabel:s.lastReport.workspaceLabel,autoBlocks:s.autoBlocks,continuationBlocks:s.continuationBlocks,override:Boolean(s.override),checks:(s.lastReport.checks||[]).map(c=>({name:c.name,category:c.category,pass:c.pass,required:c.required,durationMs:c.durationMs})),blockers:s.lastReport.blockers||[]});return{enabled:this.config.enabled,mode:this.config.mode,gateSubagents:this.config.gateSubagents,sessions,blocked:sessions.filter(x=>!x.pass).length,passed:sessions.filter(x=>x.pass).length}}
 start(){
  try{this.disposers.push(this.ctx.provide('completionGate',{run:(agent,opts)=>this.run(agent,new AbortController().signal,opts),snapshot:()=>this.snapshot()}))}catch{}
  this.disposers.push(this.ctx.tools.register({name:'completion_gate',description:'Run, inspect, or attest the production-readiness completion gate.',parameters:{type:'object',additionalProperties:false,properties:{action:{type:'string',enum:['run','status','attest']},reviewed_files:{type:'array',items:{type:'string'}},review_summary:{type:'string'},acceptance_criteria:{type:'array',items:{type:'object',additionalProperties:false,properties:{criterion:{type:'string'},evidence:{type:'string'}},required:['criterion','evidence']}},unresolved_issues:{type:'array',items:{type:'string'}}},required:['action']},output:{schema:{type:'object'},render:(_a,v)=>[{type:'text',text:v.markdown}]},execute:async(args,exec)=>{let r;if(args.action==='attest')r=await this.attest(exec.agent,args);else if(args.action==='status')r=this.state(exec.agent).lastReport||await this.run(exec.agent,exec.signal);else r=await this.run(exec.agent,exec.signal,{force:true});return{pass:r.pass,fingerprint:r.fingerprint,blockers:r.blockers,markdown:reportMarkdown(r)}}}));
  const command=(name,description,handler)=>{try{this.disposers.push(this.ctx.commands.register({name,description,...handler}))}catch{}}
  command('gate','Run Completion Gate now.',{handler:async inv=>{if(!inv.agent)return{kind:'error',text:'No active agent.'};const r=await this.run(inv.agent,new AbortController().signal,{force:true});return{kind:'success',text:reportMarkdown(r)}}})
  command('gate-status','Show the latest Completion Gate report.',{handler:async inv=>{if(!inv.agent)return{kind:'error',text:'No active agent.'};const r=this.state(inv.agent).lastReport||await this.run(inv.agent,new AbortController().signal);return{kind:'success',text:reportMarkdown(r)}}})
  command('gate-reset','Discard Completion Gate evidence for this session.',{handler:inv=>{if(!inv.agent)return{kind:'error',text:'No active agent.'};this.reset(inv.agent);return{kind:'success',text:'# Completion Gate\n\nEvidence reset.'}}})
  command('gate-override','Operator override for the exact current workspace fingerprint.',{input:{hint:'reason'},handler:async inv=>{if(!inv.agent)return{kind:'error',text:'No active agent.'};const r=await this.override(inv.agent,inv.rawInput||'Operator override');return{kind:'success',text:reportMarkdown(r)}}})
  this.disposers.push(this.ctx.systemPrompt.section({name:'tool:completion-gate',order:188,text:'For code-changing tasks, Completion Gate is authoritative before claiming completion. Do not voluntarily stop immediately after stating pending work such as “now I need”, “next I will”, or “let me inspect”; execute those actions first. Never end on reasoning-only output after tool use. When genuinely finished, call completion_gate action=attest with all changed files reviewed and acceptance criteria mapped to concrete evidence.'}));
  this.disposers.push(this.ctx.on('agent/session-start',({agent})=>{void this.baseline(agent)}));
  this.disposers.push(this.ctx.on('agent/request',async(payload,next)=>{await this.baseline(payload.agent);return next()}));
  this.disposers.push(this.ctx.on('agent/turn-stopping',p=>this.stopping(p)));
  this.disposers.push(this.ctx.webServer.register({kind:'exact',path:API,handler:(req,res)=>{if(req.method!=='GET')return json(res,405,{ok:false});if(!sameOrigin(req))return json(res,403,{ok:false});json(res,200,{ok:true,...this.snapshot()})}}))
 }
 dispose(){for(const d of this.disposers.splice(0).reverse())try{d?.()}catch{}}
}
export function apply(ctx,config={}){const s=new CompletionGateService(ctx,config);s.start();ctx.effect?.(()=>()=>s.dispose(),'completion-gate')}
