import { execFile, exec as execShell } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { promisify } from 'node:util'
import { addedLinesFromDiff, detectChecks, hashParts, parseStatusPorcelain, redactText, scanSecurity, scanTodos } from './core.js'
const execFileP=promisify(execFile),execShellP=promisify(execShell)
async function git(cwd,args,timeout=30000){try{const{stdout,stderr}=await execFileP('git',args,{cwd,timeout,maxBuffer:20*1024*1024,windowsHide:true});return{ok:true,stdout:String(stdout||''),stderr:String(stderr||'')}}catch(e){return{ok:false,stdout:String(e?.stdout||''),stderr:String(e?.stderr||e?.message||'')}}}
async function untrackedHash(cwd,files){const parts=[];for(const rel of files.slice(0,200)){try{const full=path.resolve(cwd,rel),st=fs.statSync(full);if(!st.isFile())continue;parts.push(rel,String(st.size),String(st.mtimeMs));if(st.size<=2*1024*1024)parts.push(fs.readFileSync(full))}catch{}}return hashParts(parts)}
export async function inspectWorkspace(cwd,c,baselineHead=''){const root=await git(cwd,['rev-parse','--show-toplevel']);if(!root.ok)return{isGit:false,root:cwd,head:'',status:'',diff:'',changedFiles:[],fingerprint:hashParts([cwd])};const repo=root.stdout.trim();const[head,status]=await Promise.all([git(repo,['rev-parse','HEAD']),git(repo,['status','--porcelain=v1','--untracked-files=all'])]);const current=head.stdout.trim();let base='HEAD';if(baselineHead&&baselineHead!==current&&(await git(repo,['cat-file','-e',`${baselineHead}^{commit}`])).ok)base=baselineHead;const[diff,names]=await Promise.all([git(repo,['diff','--no-ext-diff','--binary','--no-color',base,'--']),git(repo,['diff','--name-only',base,'--'])]);const statusFiles=parseStatusPorcelain(status.stdout,c.maxChangedFiles);const tracked=names.ok?names.stdout.split(/\r?\n/).map(v=>v.trim()).filter(Boolean):[];const changed=[...new Set([...tracked,...statusFiles])].slice(0,c.maxChangedFiles);const untracked=status.stdout.split(/\r?\n/).filter(l=>l.startsWith('?? ')).map(l=>l.slice(3).trim()).filter(Boolean);const uh=await untrackedHash(repo,untracked);return{isGit:true,root:repo,head:current,status:status.stdout,diff:diff.stdout,changedFiles:changed,fingerprint:hashParts([current,status.stdout,diff.stdout,uh]),diffBase:base}}
async function runCheck(check,cwd,c,signal){const start=Date.now();try{const{stdout,stderr}=await execShellP(check.command,{cwd,timeout:c.commandTimeoutMs,maxBuffer:20*1024*1024,windowsHide:true,shell:process.platform==='win32'?'cmd.exe':'/bin/sh',...(signal?{signal}:{})});return{...check,pass:true,durationMs:Date.now()-start,output:redactText(`${stdout||''}${stderr?`\n${stderr}`:''}`,cwd,c.maxOutputChars)}}catch(e){return{...check,pass:false,durationMs:Date.now()-start,output:redactText(`${e?.stdout||''}${e?.stderr?`\n${e.stderr}`:`\n${e?.message||e}`}`,cwd,c.maxOutputChars)}}}
function untrackedLines(ws){const out=[];for(const rel of ws.status.split(/\r?\n/).filter(l=>l.startsWith('?? ')).map(l=>l.slice(3).trim()).slice(0,100)){try{const full=path.resolve(ws.root,rel),st=fs.statSync(full);if(!st.isFile()||st.size>1024*1024)continue;const b=fs.readFileSync(full);if(b.includes(0))continue;out.push(...b.toString('utf8').split(/\r?\n/))}catch{}}return out}
export async function runMachineGate(ws,c,signal){const checks=detectChecks(ws.root,c),results=[];for(const check of checks)results.push(await runCheck(check,ws.root,c,signal));const added=[...addedLinesFromDiff(ws.diff),...untrackedLines(ws)];const todoHits=c.blockNewTodos?scanTodos(added):[],securityHits=c.securityScan?scanSecurity(added):[],blockers=[];if(c.requireTests&&!results.some(r=>r.category==='test'))blockers.push('No executable test command was detected for this project.');for(const r of results)if(r.required&&!r.pass)blockers.push(`${r.name} failed.`);if(todoHits.length)blockers.push(`${todoHits.length} new TODO/FIXME/HACK/XXX marker(s) detected.`);if(securityHits.length)blockers.push(`${securityHits.length} obvious security-risk pattern(s) detected in added code.`);return{workspaceLabel:path.basename(ws.root)||'workspace',fingerprint:ws.fingerprint,changedFiles:ws.changedFiles,checks:results,todoHits,securityHits,blockers,machinePass:!blockers.length,generatedAt:Date.now()}}
